[features]
seeds = false
skip-lint = false

[programs.localnet]
dynamic_bonding_curve = "DBCg4ugDEztk6MbqHEJvx5a5YGJTj45Jb5NvtQ48Rvsf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "keys/local/upgrade-authority-live.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
ixdata = "yarn run tsx --tsconfig ./tsconfig.json ./scripts/generate_ix_data_for_tests.ts"

[toolchain]
anchor_version = "0.31.0"
solana_version = "2.3.13"
